#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProjectTest2_nov7.Resource", IsApplication=true)]

namespace ProjectTest2_nov7
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Blank = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Mother_Male_1 = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001b
			public const int BackToLanguages = 2131099675;
			
			// aapt resource value: 0x7f06000d
			public const int BackToMandarin = 2131099661;
			
			// aapt resource value: 0x7f06001c
			public const int EnterAppButton = 2131099676;
			
			// aapt resource value: 0x7f06000e
			public const int MandarinText = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int Mandarin_Ma = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int PlayBack = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int PlayMa = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int Record = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int SelectFemale = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int SelectMale = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int SelectMandarin = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int Stop = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int button10 = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int button2 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int button3 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int button4 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int button5 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int button6 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int button7 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int button8 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int button9 = 2131099673;
			
			// aapt resource value: 0x7f060006
			public const int imageView1 = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout1 = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int scrollView2 = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int space1 = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int space2 = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int tableLayout1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int tableRow1 = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GenderSelect = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LanguageSelect = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Mandarin_Mother_Male = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MandarinWords = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int WelcomePage = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int mother = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int test = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int EnterApp = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
